# Generated by Django 5.2.3 on 2025-07-27 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0004_player_assists_player_goals'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='clean_sheats',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
